### ISSUE TITLE
Test jaws runtime api for submitting workflows programmatically

### ISSUE THREAD

**Issue by Michal-Babins** [microbiomedata/ReadsQC#13]
Test out use cases of JAWS api for running workflows on cori: http://jaws.lbl.gov:5003/api/v2/ui/#/

**Comment by ssarrafan** [comment]
@Michal-Babins I'm adding this to the next sprint. If you think you'll be done this week let me know.

**Comment by ssarrafan** [comment]
Removing from sprint and to backlog based on werkflow automation meeting update from @Michal-Babins.  Waiting on updates from JAWS. Michal expects to be able to pick this up early 2023.

**Comment by aclum** [comment]
@scanon  is testing the JAWS API this sprint.

**Comment by aclum** [comment]
Shane got the submit API working but the readsqc workflow needs some fixes from the jaws team first, outlined in https://github.com/microbiomedata/issues/issues/336

@scanon  do you want me to backlog this or will you work on this next sprint w/a  different wdl?

**Comment by aclum** [comment]
Backlogging this until readqc filter JAWS issues are addressed.

**Comment by aclum** [comment]
Closing this as not planned, we are switching to the JAWS client library, not the API.
