### ISSUE TITLE
create human readable methods readme for readsqc

### ISSUE THREAD

**Issue by aclum** [microbiomedata/ReadsQC#14]
The comments in https://github.com/microbiomedata/ReadbasedAnalysis/issues/14 describe some examples of methods readmes. These should be generated by the workflow and stored along with the final output files.

**Comment by chienchi** [comment]
here my [attempt](https://github.com/microbiomedata/ReadsQC/commit/99694be4a4881a67b9e9d40b9282ed4f5e06d50a) to add make_info task.  

```
BBTools(1) version 38.96
The steps below recapitulate the output of RQCFilter2 when run like this:
rqcfilter2.sh jni=t threads=4 cf=f jni=t in=SRR7877884-int-0.1.fastq.gz path=filtered rna=f trimfragadapter=t qtrim=r trimq=0 maxns=3 maq=3 minlen=51 mlf=0.33 phix=t removehuman=t removedog=t removecat=t removemouse=t khist=t removemicrobes=t sketch kapa=t clumpify=t tmpdir= barcodefilter=f trimpolyg=5 usejni=frqcfilterdata=/databases/RQCFilterData
Data dependencies are available at http://portal.nersc.gov/dna/microbial/assembly/bushnell/RQCFilterData.tar

(1) B. Bushnell: BBTools software package, http://bbtools.jgi.doe.gov/
```

**Comment by aclum** [comment]
Looks good to me.

**Comment by aclum** [comment]
What branch are you working in? Is this going to get merged into the werkflow branch?

**Comment by chienchi** [comment]
It is in branch make_info. I have create a pull request into workflow.
