### ISSUE TITLE
Workflows - Test large data sets for workflows (ReadQC)

### ISSUE THREAD

**Issue by ssarrafan** [microbiomedata/ReadsQC#2]
create a large test data set with expected outcome if workflow run is successful

link test results to this issue

**Comment by chienchi** [comment]
commit 21ad21cb7ce97683885ab992cd00af0508324436

**Comment by ssarrafan** [comment]
@hubin-keio I see there is a commit on this one. Can this issue be closed?  Or should I move it to the next sprint?
