### ISSUE TITLE
stats files for mongo for short read workflow

### ISSUE THREAD

**Issue by aclum** [microbiomedata/ReadsQC#39]
for the short read workflow we need to capture ~{prefix}_qa_stats.json from finish_rqc to the final workflow output so the workflow automation can pick up the statistics, nmdc_automation is expecting this file to be named 'stats'

**Comment by vlilanl** [comment]
Do you want us to rename this output to stats?
<img width="654" alt="Screenshot 2024-10-08 at 10 29 16" src="https://github.com/user-attachments/assets/6c1a774f-7a52-4cfa-b07b-8deeefd66777">

https://github.com/microbiomedata/ReadsQC/blob/ddc0cd9f79cc53aa9cf25b40cf67196b5cd71a29/rqcfilter.wdl#L39C15-L39C39

**Comment by aclum** [comment]
Do you have a test run? The issue is that we need ~{prefix}_qa_stats.json from finish_rqc (https://github.com/microbiomedata/ReadsQC/blob/ddc0cd9f79cc53aa9cf25b40cf67196b5cd71a29/shortReadsqc.wdl#L304) to be an output from the finish_rqc task and then have that passed to the final workflow output.

The stats json that we need has keys that match up with the schema stats. see https://microbiomedata.github.io/nmdc-schema/ReadQcAnalysis/
so we need the json with keys of 'input_read_count', 'input_read_bases','output_read_count','output_read_bases'

**Comment by aclum** [comment]
It doesn't look like the same file is being generated for the long reads workflow so that will be a separate ticket to update scripts in the microbiomedata/workflowmeta to generate the same stats file.

**Comment by ssarrafan** [comment]
@vlilanl will this be done by tomorrow?

**Comment by vlilanl** [comment]
Perlmutter is down so I cannot test anything at the moment, I do hope to close these tickets tomorrow as long as testing goes smoothly.
